In [1]:
import pandas as pd
import numpy as np

In [2]:
npyname = "kddi_all_new_0320max" #kddi_00_new_0315_15min
datedir = "230316"

In [3]:
# 交通量データの読込み
csv_file = r'./'+datedir+'/'+npyname+'.csv'
df = pd.read_csv(csv_file, dtype={'date':str}, index_col=0, parse_dates=True)

FileNotFoundError: [Errno 2] No such file or directory: './230316/kddi_all_new_0320max.csv'

In [94]:
# 読み込んだデータの確認
df

                        osm_id       tbran
times
2022-04-01 00:00:00   46344678   20.174948
2022-04-01 00:00:00   52458736   16.832668
2022-04-01 00:00:00   52463146    4.545632
2022-04-01 00:00:00   52463153   17.797780
2022-04-01 00:00:00   54818301   11.586467
...                        ...         ...
2022-04-01 23:45:00  702526908  129.861180
2022-04-01 23:45:00  702526909   94.261470
2022-04-01 23:45:00  702526910   94.261470
2022-04-01 23:45:00  702526911   94.261470
2022-04-01 23:45:00  703313024   44.365784

[82601 rows x 2 columns]

In [95]:
# 15分単位でGroup byして、結果をagg関数にsum関数を渡して集計
totalling_df = df.groupby([pd.Grouper(level='times', freq='30T'), 'osm_id']).agg(np.sum) #gridcode

In [96]:
# 集計したデータの確認
totalling_df

                                    tbran
times               osm_id
2022-04-01 00:00:00 46344678    47.757378
                    52458736    37.525877
                    52463146     8.118440
                    52463153    39.968266
                    54818301    21.902377
...                                   ...
2022-04-01 23:30:00 702526908  230.546765
                    702526909  126.170250
                    702526910  147.024580
                    702526911  126.170250
                    703313024   83.487088

[42606 rows x 1 columns]

In [97]:
totalling_df.to_csv(datedir+'/'+npyname+'totalling_df_osm.csv')

In [98]:
# 行列の入れ替え
output_df = totalling_df.unstack(fill_value=0)

In [99]:
output_df = output_df.fillna(0)

In [100]:
# 行列入れ替え後のデータを確認
output_df

                           tbran                                       \
osm_id                27755814    27755914    27808255     27808268
times
2022-04-01 00:00:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 00:30:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 01:00:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 01:30:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 02:00:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 02:30:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 03:00:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 03:30:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 04:00:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 04:30:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 05:00:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 05:30:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 06:00:00   204.084568    0.000000  159.260655  1704.088165
2022-04-01 06:30:00  1226.220192   51.636184  186.577555   608.807422
2022-04-01 07:00:00   755.407359  234.267717  522.501918   988.424054
2022-04-01 07:30:00  2077.551393  376.623357  616.904348  1692.601602
2022-04-01 08:00:00  1383.316672    0.915878  407.032487  1353.347082
2022-04-01 08:30:00   954.230794  179.079944  663.795343  1250.322692
2022-04-01 09:00:00   917.877879  205.547044  513.715498  1127.555275
2022-04-01 09:30:00  1158.876270  454.163115  622.130740  1835.204500
2022-04-01 10:00:00   968.032521   87.054046  517.245611   909.158083
2022-04-01 10:30:00  1007.009694  282.722166  726.507443  2248.670087
2022-04-01 11:00:00   210.633658   18.540620  627.173535   933.438034
2022-04-01 11:30:00   716.881307   10.496353  470.904513  1363.300510
2022-04-01 12:00:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 12:30:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 13:00:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 13:30:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 14:00:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 14:30:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 15:00:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 15:30:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 16:00:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 16:30:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 17:00:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 17:30:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 18:00:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 18:30:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 19:00:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 19:30:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 20:00:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 20:30:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 21:00:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 21:30:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 22:00:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 22:30:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 23:00:00     0.000000    0.000000    0.000000     0.000000
2022-04-01 23:30:00     0.000000    0.000000    0.000000     0.000000

                                                                         \
osm_id                38135611     38135612     38135616     38135912
times
2022-04-01 00:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 00:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 01:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 01:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 02:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 02:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 03:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 03:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 04:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 04:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 05:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 05:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 06:00:00     0.000000   265.729153   716.131654   571.245186
2022-04-01 06:30:00    84.355736   343.000000   972.537121  2785.952178
2022-04-01 07:00:00   201.534277   429.956832  2984.640925  1543.004529
2022-04-01 07:30:00   647.000000   976.213947  1129.943924  4030.839258
2022-04-01 08:00:00  1030.515737  1582.593041  1577.406911  1113.108519
2022-04-01 08:30:00   342.392051   706.231348   738.600818  1927.765718
2022-04-01 09:00:00   665.540234   577.934381  1434.361296  2232.653869
2022-04-01 09:30:00   527.799246   788.357982  2023.654850  3438.105575
2022-04-01 10:00:00   604.120820   339.876638  5035.311976  2591.932184
2022-04-01 10:30:00   314.943568  1040.489650  1119.378953  1852.910369
2022-04-01 11:00:00   421.689482   644.849089  2973.555187  2791.913266
2022-04-01 11:30:00   249.950808   438.513454  1690.812263  2032.908991
2022-04-01 12:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 12:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 13:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 13:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 14:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 14:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 15:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 15:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 16:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 16:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 17:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 17:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 18:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 18:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 19:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 19:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 20:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 20:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 21:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 21:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 22:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 22:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 23:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 23:30:00     0.000000     0.000000     0.000000     0.000000

                                               ...                            \
osm_id                38135927     38135933    ...   1025576170   1025576171
times                                          ...
2022-04-01 00:00:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 00:30:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 01:00:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 01:30:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 02:00:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 02:30:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 03:00:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 03:30:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 04:00:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 04:30:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 05:00:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 05:30:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 06:00:00   266.530933   159.965446  ...   370.210167   370.210167
2022-04-01 06:30:00  1123.983799   947.109650  ...   435.384487   466.379036
2022-04-01 07:00:00  3101.283537  2485.223605  ...   426.053719   575.119192
2022-04-01 07:30:00  1653.399009  1095.941759  ...  1411.196284  1411.196284
2022-04-01 08:00:00  1728.805382   474.177501  ...  1377.221300  1477.110215
2022-04-01 08:30:00  1858.192978  1160.004262  ...  1357.827048  1357.827048
2022-04-01 09:00:00  2444.630204  1634.858225  ...  1305.199112  1807.971755
2022-04-01 09:30:00  2354.386920  1807.262769  ...  1463.503910  1463.503910
2022-04-01 10:00:00  3395.876398  2233.375730  ...  1045.681608  1263.770614
2022-04-01 10:30:00  2125.155884  1007.595915  ...  1636.716017  1636.716017
2022-04-01 11:00:00  1657.391473  1657.391473  ...  1594.144202  1594.144202
2022-04-01 11:30:00  1846.996720  1779.266894  ...  1428.597460  1683.947926
2022-04-01 12:00:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 12:30:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 13:00:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 13:30:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 14:00:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 14:30:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 15:00:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 15:30:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 16:00:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 16:30:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 17:00:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 17:30:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 18:00:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 18:30:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 19:00:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 19:30:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 20:00:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 20:30:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 21:00:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 21:30:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 22:00:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 22:30:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 23:00:00     0.000000     0.000000  ...     0.000000     0.000000
2022-04-01 23:30:00     0.000000     0.000000  ...     0.000000     0.000000

                                                                         \
osm_id                1025576177   1025576178   1076509246   1076509247
times
2022-04-01 00:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 00:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 01:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 01:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 02:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 02:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 03:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 03:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 04:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 04:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 05:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 05:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 06:00:00   222.606782   120.014459   523.839214   132.805828
2022-04-01 06:30:00   270.729770  1303.802126   659.666119   331.247711
2022-04-01 07:00:00   581.470353  1527.999275   615.932360  1679.575230
2022-04-01 07:30:00   727.991634  1028.020967  1074.961936   753.544429
2022-04-01 08:00:00   652.467105   703.527623   926.725506   583.370358
2022-04-01 08:30:00   971.782853  1038.654201  1732.500430   659.030570
2022-04-01 09:00:00   520.009134   562.184973  1249.907565   817.514589
2022-04-01 09:30:00   759.030285   544.815995  1502.404016   664.481550
2022-04-01 10:00:00   724.432835   570.706040   689.316243   955.171716
2022-04-01 10:30:00  1097.943483   704.943289   858.511196   489.609095
2022-04-01 11:00:00   558.915932   813.035440  1494.852374  1328.135540
2022-04-01 11:30:00   703.978778  1013.144418   741.189315  1246.965584
2022-04-01 12:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 12:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 13:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 13:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 14:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 14:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 15:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 15:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 16:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 16:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 17:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 17:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 18:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 18:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 19:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 19:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 20:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 20:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 21:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 21:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 22:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 22:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 23:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 23:30:00     0.000000     0.000000     0.000000     0.000000


osm_id                1083697941   1083697942   1083697943   1083697944
times
2022-04-01 00:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 00:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 01:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 01:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 02:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 02:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 03:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 03:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 04:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 04:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 05:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 05:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 06:00:00   227.435101   227.435101   227.435101   227.435101
2022-04-01 06:30:00   987.870018   987.870018   987.870018   987.870018
2022-04-01 07:00:00  2099.710557  2099.710557  2099.710557  2099.710557
2022-04-01 07:30:00  1863.093621  1863.093621  1863.093621  1863.093621
2022-04-01 08:00:00  1335.825991  1015.637640  1015.637640  1015.637640
2022-04-01 08:30:00  4320.611111  1977.721324  1977.721324  1977.721324
2022-04-01 09:00:00  1702.523446  1727.528271  1350.736469  1350.736469
2022-04-01 09:30:00  1231.853313  1231.853313  1231.853313  1231.853313
2022-04-01 10:00:00  1052.490373  1100.918630  1052.490373  1052.490373
2022-04-01 10:30:00  1026.651554  1026.651554  1026.651554  1026.651554
2022-04-01 11:00:00  1306.616978  1306.616978  1306.616978  1306.616978
2022-04-01 11:30:00   870.471933   769.939594   769.939594   769.939594
2022-04-01 12:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 12:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 13:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 13:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 14:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 14:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 15:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 15:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 16:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 16:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 17:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 17:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 18:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 18:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 19:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 19:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 20:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 20:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 21:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 21:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 22:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 22:30:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 23:00:00     0.000000     0.000000     0.000000     0.000000
2022-04-01 23:30:00     0.000000     0.000000     0.000000     0.000000

[48 rows x 3170 columns]

In [89]:
output_df.to_csv(datedir+'/'+npyname + "_header.csv")

In [90]:
# numpy_arrayに変換
output_nd = output_df.to_numpy()

In [91]:
output_nd.astype(np.double)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [77]:
# numpy_arrayに変換したデータの確認
output_nd

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [78]:
#正規化データの保存
from sklearn.preprocessing import MinMaxScaler
# データの正規化
# データを0～1の範囲に正規化）
scaler = MinMaxScaler(feature_range=(0, 1))
np.save(datedir+'/'+npyname + '_01weight.npy', scaler.fit_transform(output_nd))

In [79]:
# データの保存
np.save(datedir+'/'+npyname + '_01param.npy', output_nd)